/**
 * 共有レシピページの HTML レンダリング（docs/Web共有設計.md §4）。
 *
 * - 全フィールドを HTML エスケープ（ユーザー入力をそのまま埋め込まない）
 * - noindex（meta とヘッダの両方 — ルート側で X-Robots-Tag も付ける）
 * - OGP: SNS に貼るとタイトル・説明・写真のカードで展開される
 * - ブランド準拠のダーク配色（docs/brand/ロゴ仕様.md）・UI 表記は DAIDOKO
 */
import type { SharedBookRecipeRow, SharedBookRow, SharedRecipeRow } from './share-store.js';

const PLAY_STORE_URL = 'https://play.google.com/store/apps/details?id=com.daidoko.app';

/**
 * 「アプリで保存」の遷移先。iOS から見ているなら App Store へ送りたいが、
 * **公開前の App Store URL は 404 になる**ので、`SHARE_APP_STORE_URL` を
 * 設定するまでは全員 Play へ送る（iOS 公開時に env を入れるだけで切り替わる）。
 */
export function storeUrlForUserAgent(userAgent: string | undefined): string {
  const appStore = process.env['SHARE_APP_STORE_URL'];
  if (!appStore || appStore.trim() === '') return PLAY_STORE_URL;
  return /iPhone|iPad|iPod/i.test(userAgent ?? '') ? appStore : PLAY_STORE_URL;
}

const STRINGS = {
  ja: {
    servings: (n: number) => `${n}人分`,
    cookTime: (n: number) => `約${n}分`,
    ingredients: '材料',
    steps: '作り方',
    memo: 'メモ',
    cta: 'アプリでこのレシピを保存',
    ctaSub: 'だいどこ — 家族で育てる、台所のレシピ手帳',
    footer:
      'このページは投稿者が共有したレシピです。投稿者が共有を停止すると表示されなくなります。',
    aiCoverNotice: 'AIが作ったイメージです',
    // アプリ内の `ai.disclaimer` と**同一の文**。共有ページは作った本人以外が読む面なので
    // ここを弱めない（アレルゲンの検出はしないので、この一文が唯一の警告）
    aiRecipeNotice:
      'AIが推定したレシピです。材料・分量・手順は必ずご確認ください（アレルギーのある方は特にご注意ください）。',
    notFound: 'このレシピは見つかりませんでした',
    notFoundBody: 'リンクが間違っているか、投稿者が共有を停止しました。',
    toc: '収録レシピ',
    bookCta: 'アプリでレシピ帖をつくる',
    bookFooter:
      'このページは投稿者が共有したレシピ帖です。投稿者が共有を停止すると表示されなくなります。',
    protectedTitle: '保護されたレシピ帖',
    passcodePrompt:
      'このレシピ帖はパスコードで保護されています。投稿者から聞いた数字のパスコードを入力してください。',
    passcodeLabel: 'パスコード',
    passcodeSubmit: '開く',
    passcodeWrong: 'パスコードが違います。',
    passcodeLocked: '試行回数が多すぎます。しばらく待ってからやり直してください。',
  },
  en: {
    servings: (n: number) => `Serves ${n}`,
    cookTime: (n: number) => `About ${n} min`,
    ingredients: 'Ingredients',
    steps: 'Steps',
    memo: 'Notes',
    cta: 'Save this recipe in the app',
    ctaSub: 'DAIDOKO — a family recipe notebook',
    footer: 'This recipe was shared by its author. It disappears when the author stops sharing.',
    aiCoverNotice: 'This image was created by AI',
    aiRecipeNotice:
      'This recipe was generated by AI. Always check the ingredients, amounts and steps yourself — especially if you have food allergies.',
    notFound: 'Recipe not found',
    notFoundBody: 'The link may be wrong, or the author stopped sharing it.',
    toc: 'Recipes in this book',
    bookCta: 'Make your own recipe book in the app',
    bookFooter:
      'This recipe book was shared by its author. It disappears when the author stops sharing.',
    protectedTitle: 'Protected recipe book',
    passcodePrompt:
      'This recipe book is protected with a passcode. Enter the numeric passcode you received from the author.',
    passcodeLabel: 'Passcode',
    passcodeSubmit: 'Open',
    passcodeWrong: 'Wrong passcode.',
    passcodeLocked: 'Too many attempts. Please wait a while and try again.',
  },
} as const;

export function escapeHtml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

const PAGE_CSS = `
  :root { color-scheme: dark; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { background: #0A0805; color: #DCC9A8; font-family: 'Hiragino Mincho ProN', 'Yu Mincho', serif;
         line-height: 1.8; -webkit-font-smoothing: antialiased; }
  .wrap { max-width: 640px; margin: 0 auto; padding: 24px 20px 48px; }
  .brand { font-family: Georgia, 'Times New Roman', serif; font-style: italic; letter-spacing: 0.35em;
           color: #C9A16A; font-size: 13px; text-align: center; padding: 8px 0 20px;
           border-bottom: 1px solid #2E2418; }
  .photo { width: 100%; border-radius: 12px; margin: 20px 0 4px; display: block; }
  .ai-cover-notice { color: #8A7A5E; font-size: 11px; letter-spacing: 0.05em; margin: 0 0 4px; }
  /* 中身が AI 由来の注意書き。表紙の注記より強い — 材料と分量の安全に関わる */
  .ai-recipe-notice { color: #DCC9A8; font-size: 12px; line-height: 1.7; margin: 20px 0 0;
       padding: 10px 12px; border: 1px solid #2E2418; border-left: 3px solid #C9A16A; }
  h1 { color: #F0E2C8; font-size: 26px; font-weight: 600; margin: 20px 0 6px; }
  .meta { color: #8A7A5E; font-size: 13px; margin-bottom: 4px; }
  .tags { color: #8A7A5E; font-size: 12px; }
  h2 { color: #C9A16A; font-size: 15px; letter-spacing: 0.15em; margin: 28px 0 10px;
       padding-bottom: 6px; border-bottom: 1px solid #2E2418; }
  ul.ings { list-style: none; }
  ul.ings li { display: flex; justify-content: space-between; gap: 12px;
               padding: 7px 0; border-bottom: 1px dotted #2E2418; font-size: 15px; }
  ul.ings .amt { color: #8A7A5E; white-space: nowrap; }
  .grp { color: #C9A16A; font-size: 13px; margin-top: 10px; }
  ol.steps { list-style: none; counter-reset: s; }
  ol.steps li { counter-increment: s; display: flex; gap: 12px; padding: 10px 0; font-size: 15px; }
  ol.steps li::before { content: counter(s); color: #C9A16A; font-family: Georgia, serif;
                        font-style: italic; font-size: 18px; min-width: 22px; }
  .memo { font-size: 14px; color: #B8A585; white-space: pre-wrap; }
  .cta { display: block; text-align: center; background: #C9A16A; color: #0A0805;
         text-decoration: none; border-radius: 10px; padding: 14px 16px; font-weight: 700;
         font-size: 15px; margin: 36px 0 8px; }
  .cta-sub { text-align: center; color: #8A7A5E; font-size: 12px; }
  .footer { margin-top: 40px; padding-top: 14px; border-top: 1px solid #2E2418;
            color: #6A5C44; font-size: 11px; text-align: center; }
`;

interface SharedIngredient {
  name: string;
  amount?: string;
  note?: string;
  groupLabel?: string;
}

function parseJsonArray<T>(json: string): T[] {
  try {
    const parsed: unknown = JSON.parse(json);
    return Array.isArray(parsed) ? (parsed as T[]) : [];
  } catch {
    return [];
  }
}

function renderIngredients(ings: SharedIngredient[], _locale: 'ja' | 'en'): string {
  const items: string[] = [];
  let lastGroup = '';
  for (const ing of ings) {
    const group = ing.groupLabel?.trim() ?? '';
    if (group && group !== lastGroup) {
      items.push(`<li class="grp">${escapeHtml(group)}</li>`);
    }
    lastGroup = group;
    const amount = [ing.amount, ing.note ? `（${ing.note}）` : ''].filter(Boolean).join(' ').trim();
    items.push(
      `<li><span>${escapeHtml(ing.name)}</span><span class="amt">${escapeHtml(amount)}</span></li>`,
    );
  }
  return items.join('\n');
}

export function renderSharePage(
  row: SharedRecipeRow,
  baseUrl: string,
  storeUrl: string = PLAY_STORE_URL,
): string {
  const locale = row.locale === 'en' ? 'en' : 'ja';
  const s = STRINGS[locale];
  const title = escapeHtml(row.title);
  const ingredients = parseJsonArray<SharedIngredient>(row.ingredientsJson);
  const steps = parseJsonArray<{ body: string }>(row.stepsJson);
  const tags = parseJsonArray<string>(row.tagsJson);

  const metaParts = [
    row.servings != null ? s.servings(row.servings) : null,
    row.cookTimeMin != null ? s.cookTime(row.cookTimeMin) : null,
  ].filter(Boolean);

  // OGP の説明: メモがあればそれ、無ければ材料名のプレビュー
  const ogDescription = escapeHtml(
    (
      row.description?.trim() ||
      ingredients
        .slice(0, 6)
        .map((i) => i.name)
        .join('・')
    ).slice(0, 120),
  );
  const photoUrl = row.photo ? `${baseUrl}/r/${row.slug}/photo` : null;
  const aiCover = photoUrl != null && row.coverIsAiGenerated === 1;

  return `<!doctype html>
<html lang="${locale}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>${title} | DAIDOKO</title>
<meta property="og:type" content="article">
<meta property="og:title" content="${title}">
<meta property="og:description" content="${ogDescription}">
<meta property="og:site_name" content="DAIDOKO">
${photoUrl ? `<meta property="og:image" content="${escapeHtml(photoUrl)}">\n<meta name="twitter:card" content="summary_large_image">` : `<meta name="twitter:card" content="summary">`}
<style>${PAGE_CSS}</style>
</head>
<body>
<div class="wrap">
  <div class="brand">DAIDOKO</div>
  ${photoUrl ? `<img class="photo" src="${escapeHtml(photoUrl)}" alt="${title}">` : ''}
  ${aiCover ? `<p class="ai-cover-notice">${s.aiCoverNotice}</p>` : ''}
  <h1>${title}</h1>
  ${metaParts.length > 0 ? `<div class="meta">${escapeHtml(metaParts.join(' ・ '))}</div>` : ''}
  ${tags.length > 0 ? `<div class="tags">${escapeHtml(tags.map((t) => `#${t}`).join(' '))}</div>` : ''}
  ${row.aiGenerated === 1 ? `<p class="ai-recipe-notice">${s.aiRecipeNotice}</p>` : ''}
  ${
    ingredients.length > 0
      ? `<h2>${s.ingredients}</h2>\n<ul class="ings">${renderIngredients(ingredients, locale)}</ul>`
      : ''
  }
  ${
    steps.length > 0
      ? `<h2>${s.steps}</h2>\n<ol class="steps">${steps
          .map((st) => `<li><span>${escapeHtml(st.body)}</span></li>`)
          .join('\n')}</ol>`
      : ''
  }
  ${
    row.description?.trim()
      ? `<h2>${s.memo}</h2>\n<p class="memo">${escapeHtml(row.description.trim())}</p>`
      : ''
  }
  <a class="cta" href="${escapeHtml(storeUrl)}">${s.cta}</a>
  <div class="cta-sub">${s.ctaSub}</div>
  <div class="footer">${s.footer}</div>
</div>
</body>
</html>`;
}

// ── レシピ帖（S2）: 目次 ＋ 全レシピを 1 ページに ────────────────────────────

const BOOK_CSS = `
  .book-desc { color: #B8A585; font-size: 14px; margin: 6px 0 0; }
  ol.toc { list-style: none; counter-reset: t; margin: 10px 0 0; }
  ol.toc li { counter-increment: t; padding: 6px 0; border-bottom: 1px dotted #2E2418; }
  ol.toc li::before { content: counter(t) '. '; color: #C9A16A; font-family: Georgia, serif;
                      font-style: italic; }
  ol.toc a { color: #DCC9A8; text-decoration: none; }
  section.recipe { margin-top: 44px; padding-top: 8px; border-top: 1px solid #2E2418; }
  section.recipe h2.rtitle { color: #F0E2C8; font-size: 22px; font-weight: 600;
                             letter-spacing: 0; border: none; margin: 16px 0 4px; }
  h3 { color: #C9A16A; font-size: 14px; letter-spacing: 0.15em; margin: 22px 0 8px;
       padding-bottom: 6px; border-bottom: 1px solid #2E2418; }
`;

export function renderBookPage(
  book: SharedBookRow,
  bookRecipes: SharedBookRecipeRow[],
  baseUrl: string,
  storeUrl: string = PLAY_STORE_URL,
): string {
  const locale = book.locale === 'en' ? 'en' : 'ja';
  const s = STRINGS[locale];
  const title = escapeHtml(book.title);
  const ogDescription = escapeHtml(
    (book.description?.trim() || bookRecipes.map((r) => r.title).join('・')).slice(0, 120),
  );
  const firstPhotoIndex = bookRecipes.findIndex((r) => r.photo != null);
  const ogImage =
    firstPhotoIndex >= 0 ? `${baseUrl}/b/${book.slug}/photo/${firstPhotoIndex}` : null;

  const toc = bookRecipes
    .map((r, i) => `<li><a href="#r${i}">${escapeHtml(r.title)}</a></li>`)
    .join('\n');

  const sections = bookRecipes
    .map((recipe, i) => {
      const ingredients = parseJsonArray<SharedIngredient>(recipe.ingredientsJson);
      const steps = parseJsonArray<{ body: string }>(recipe.stepsJson);
      const metaParts = [
        recipe.servings != null ? s.servings(recipe.servings) : null,
        recipe.cookTimeMin != null ? s.cookTime(recipe.cookTimeMin) : null,
      ].filter(Boolean);
      const photoUrl = recipe.photo ? `${baseUrl}/b/${book.slug}/photo/${i}` : null;
      const aiCover = photoUrl != null && recipe.coverIsAiGenerated === 1;
      return `<section class="recipe" id="r${i}">
  ${photoUrl ? `<img class="photo" src="${escapeHtml(photoUrl)}" alt="${escapeHtml(recipe.title)}">` : ''}
  ${aiCover ? `<p class="ai-cover-notice">${s.aiCoverNotice}</p>` : ''}
  <h2 class="rtitle">${escapeHtml(recipe.title)}</h2>
  ${metaParts.length > 0 ? `<div class="meta">${escapeHtml(metaParts.join(' ・ '))}</div>` : ''}
  ${recipe.aiGenerated === 1 ? `<p class="ai-recipe-notice">${s.aiRecipeNotice}</p>` : ''}
  ${
    ingredients.length > 0
      ? `<h3>${s.ingredients}</h3>\n<ul class="ings">${renderIngredients(ingredients, locale)}</ul>`
      : ''
  }
  ${
    steps.length > 0
      ? `<h3>${s.steps}</h3>\n<ol class="steps">${steps
          .map((st) => `<li><span>${escapeHtml(st.body)}</span></li>`)
          .join('\n')}</ol>`
      : ''
  }
  ${
    recipe.description?.trim()
      ? `<h3>${s.memo}</h3>\n<p class="memo">${escapeHtml(recipe.description.trim())}</p>`
      : ''
  }
</section>`;
    })
    .join('\n');

  return `<!doctype html>
<html lang="${locale}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>${title} | DAIDOKO</title>
<meta property="og:type" content="article">
<meta property="og:title" content="${title}">
<meta property="og:description" content="${ogDescription}">
<meta property="og:site_name" content="DAIDOKO">
${ogImage ? `<meta property="og:image" content="${escapeHtml(ogImage)}">\n<meta name="twitter:card" content="summary_large_image">` : `<meta name="twitter:card" content="summary">`}
<style>${PAGE_CSS}${BOOK_CSS}</style>
</head>
<body>
<div class="wrap">
  <div class="brand">DAIDOKO</div>
  <h1>${title}</h1>
  ${book.description?.trim() ? `<p class="book-desc">${escapeHtml(book.description.trim())}</p>` : ''}
  <h2>${s.toc}</h2>
  <ol class="toc">${toc}</ol>
  ${sections}
  <a class="cta" href="${escapeHtml(storeUrl)}">${s.bookCta}</a>
  <div class="cta-sub">${s.ctaSub}</div>
  <div class="footer">${s.bookFooter}</div>
</div>
</body>
</html>`;
}

/**
 * パスコード入力ページ（S4-2）。帖のタイトルも OGP も出さない —
 * リンクプレビューやソースから中身が漏れないようにするため。
 */
export function renderPasscodePage(
  slug: string,
  locale: string,
  failed: boolean,
  locked = false,
): string {
  const t = locale === 'en' ? STRINGS.en : STRINGS.ja;
  const error = locked ? t.passcodeLocked : failed ? t.passcodeWrong : '';
  return `<!doctype html>
<html lang="${locale === 'en' ? 'en' : 'ja'}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>${t.protectedTitle} | DAIDOKO</title>
<style>${PAGE_CSS}
  .pass-form { margin-top: 24px; display: flex; gap: 12px; align-items: center; }
  .pass-form input {
    background: #17120C; border: 1px solid #2E2418; border-radius: 8px;
    color: #DCC9A8; font-size: 24px; letter-spacing: 8px; text-align: center;
    width: 9em; max-width: 60vw; padding: 10px 12px;
  }
  .pass-form button {
    background: #C9A16A; color: #0A0805; border: 0; border-radius: 8px;
    font-size: 16px; font-weight: 600; padding: 12px 22px; cursor: pointer;
  }
  .pass-error { margin-top: 14px; color: #E08A7A; }
</style>
</head>
<body>
<div class="wrap">
  <div class="brand">DAIDOKO</div>
  <h1>${t.protectedTitle}</h1>
  <p>${t.passcodePrompt}</p>
  <form class="pass-form" method="post" action="/b/${escapeHtml(slug)}/unlock">
    <input name="passcode" inputmode="numeric" autocomplete="one-time-code" pattern="\\d{4}|\\d{6}" maxlength="6" required aria-label="${t.passcodeLabel}">
    <button type="submit">${t.passcodeSubmit}</button>
  </form>
  ${error ? `<p class="pass-error">${error}</p>` : ''}
</div>
</body>
</html>`;
}

export function renderNotFoundPage(): string {
  // 言語は分からない（行が無い）ので日英併記
  const ja = STRINGS.ja;
  const en = STRINGS.en;
  return `<!doctype html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>${ja.notFound} | DAIDOKO</title>
<style>${PAGE_CSS}</style>
</head>
<body>
<div class="wrap">
  <div class="brand">DAIDOKO</div>
  <h1>${ja.notFound}</h1>
  <p>${ja.notFoundBody}</p>
  <p class="meta">${en.notFound} — ${en.notFoundBody}</p>
</div>
</body>
</html>`;
}
