import type ja from '../ja/ai';

const ai: typeof ja = {
  disclaimer: {
    text: 'This recipe was generated by AI. Always check the ingredients, amounts and steps yourself — especially if you have food allergies.',
    intent:
      'MUST convey that the recipe is AI-generated and UNVERIFIED, and that the user must check ' +
      'ingredients, amounts and steps themselves. MUST keep the allergy warning explicit — ' +
      'the app does NOT detect allergens, so this sentence is the only warning the user gets. ' +
      'MUST NOT be softened into a generic "powered by AI" note.',
  },

  adGate: {
    title: 'Out of free uses',
    body: 'Watch a short ad to unlock one more AI recipe.',
    watch: 'Watch ad',
  },

  error: {
    apiKey: {
      text: 'Check your API key — it may be invalid or lack permission.',
      intent:
        'MUST direct the user to check their own API key. MUST NOT be confusable with a ' +
        'temporary failure — waiting or retrying cannot fix an invalid key.',
    },

    byokQuota: {
      text: "You've reached the usage limit on your own Gemini key. Please wait and try again.",
      intent:
        "MUST make clear the limit is on the user's OWN Gemini key, not this app's quota. " +
        'MUST convey that waiting is the remedy. MUST NOT be confusable with a network failure.',
    },

    noResult: "The AI didn't return a result",
    unparsable: "We couldn't read the AI's response",
    tooLarge:
      'The photo or data you sent was too large. Retake the photo or trim the content and try again.',
    busy: "It's busy right now. Please wait a moment and try again.",
    serverDown: 'Something went wrong on the server. Please wait a moment and try again.',
    serverError: 'Server error ({{status}})',
    timeout: 'The request timed out',
    unreachable: "We couldn't reach the AI ({{reason}})",
    imageLoadFailed: "We couldn't load that image",
    draftConvertFailed: "We couldn't turn that into a recipe draft",
  },
};

export default ai;
