/**
 * Meal plan (X days of menus, #215). Design: `docs/買い物リスト・在庫設計.md` §10.
 */
const menu = {
  title: 'Meal plan',
  card: {
    nextTitle: 'Up next',
    todayTitle: "Today's plan",
    open: 'Open meal plan',
    cook: 'Cook',
    empty: 'Plan a few days of meals from what you have',
    build: 'Plan meals',
    autoGeneratedAt: 'Made automatically at {{time}} this morning',
  },
  days: {
    label: 'How many days',
    option: '{{count}} days',
  },
  mealTime: {
    label: 'Which meal',
    breakfast: 'Breakfast',
    lunch: 'Lunch',
    dinner: 'Dinner',
    planLabel: {
      breakfast: 'Breakfast plan',
      lunch: 'Lunch plan',
    },
    suffix: {
      breakfast: ' (breakfast)',
      lunch: ' (lunch)',
    },
  },
  buildResult: {
    built: {
      one: 'Planned meals for {{count}} day',
      other: 'Planned meals for {{count}} days',
    },
    partial: {
      one: 'Not enough recipes — planned only {{count}} day',
      other: 'Not enough recipes — planned only {{count}} days',
    },
  },
  shortfall: {
    banner: {
      one: 'Not enough recipes for {{count}} more day',
      other: 'Not enough recipes for {{count}} more days',
    },
    addRecipe: 'Add a recipe',
    bulkGenerate: {
      one: 'Create {{count}} missing day in one go',
      other: 'Create the missing {{count}} days in one go',
    },
  },
  bulk: {
    generating: 'Thinking up recipes…',
    failed: "We couldn't create the recipes. Your meal plan is unchanged.",
    emptyResult: "We couldn't use the AI suggestions. Your meal plan is unchanged.",
    saveFailed: "We couldn't save the recipes. Please try again.",
    sheetTitle: 'AI recipe suggestions',
    sheetBody: 'Pick the ones you want. Saved recipes fill the empty days of your plan.',
    ingredientCount: {
      one: '{{count}} ingredient',
      other: '{{count}} ingredients',
    },
    confirm: {
      one: 'Keep this {{count}} recipe',
      other: 'Keep these {{count}} recipes',
    },
    confirmNone: 'Pick at least one',
    done: {
      one: 'Created {{count}} recipe and added it to your plan',
      other: 'Created {{count}} recipes and added them to your plan',
    },
  },
  day: {
    label: 'Day {{day}}',
    openRecipe: 'Open recipe',
    replace: 'Swap',
    done: 'Cooked',
    missing: 'This recipe is gone',
    noTime: 'No time recorded',
    minutes: '{{count}} min',
  },
  reason: {
    expiry: '{{name}} is expiring soon',
    coverage: 'You already have {{count}} of the ingredients',
    pinned: "It's on your want-to-cook list",
    fewMissing: 'Only {{count}} things to buy',
    aiNew: 'Newly created by AI',
  },
  claim: {
    contested: 'Used on {{count}} days',
  },
  emptyDays: {
    title: "Couldn't plan any meals",
    noRecipes: 'No recipes yet. Add a few first.',
    fewRecipes: 'Not enough recipes, so only some days are filled',
    toConsult: 'Create one with AI',
  },
  stale: {
    message: 'Your pantry changed',
    rebuild: 'Plan again',
  },
  shopping: {
    add: 'Add all missing ingredients',
    none: 'Nothing missing',
  },
  warnEmptyPantry: 'Your pantry is empty, so this plan assumes shopping',
  swap: {
    noCandidates: 'No other recipe to swap in',
  },

  ai: {
    button: 'Let AI rearrange it',
    running: 'Rearranging…',
    failed: "We couldn't rearrange it with AI. Keeping the current plan.",
    emptyResult: "We couldn't use the AI suggestion. Keeping the current plan.",
    done: 'AI rearranged your menu plan',
    arrangedBadge: 'Arranged by AI',
    limitNote: {
      one: 'Free, {{count}} time a month',
      other: 'Free, {{count}} times a month',
    },
  },
  auto: {
    settingsButton: 'Meal plan settings',
    undo: {
      one: 'Undo {{count}} item added automatically',
      other: 'Undo {{count}} items added automatically',
    },
  },
  settings: {
    title: 'Meal plan settings',
    parentLabel: 'Daily meal plan',
    parentSubtitle: 'Keeps your plan up to date on every launch, and notifies you each morning',
    daysLabel: 'How many days to keep',
    notifyTimeLabel: 'Notification time',
    childLabel: 'Add missing ingredients automatically',
    childSubtitle:
      "One person in your family turning this on is enough. If two people turn it on, each person's missing ingredients go to the same list. It also goes to the shopping list shared with your family. Items you already have may be added sometimes — undo it with a tap from the meal plan screen.",
    tasteLabel: "Family's likes and dislikes",
    tasteSubtitle:
      'Used when AI creates recipes in one go (e.g. "no seafood", "mild spice only"). Stored only on this device — never shared with your family.',
    tastePlaceholder: 'e.g. No raw fish. Our staples are onions and carrots',
    clearAction: 'Clear meal plan',
    clearConfirmTitle: 'Clear this meal plan?',
    clearConfirmBody: "Your pantry and shopping list won't change. This can't be undone.",
  },
};

export default menu;
