/**
 * Android の自動バックアップ範囲を制御する config plugin（#79 d①）。
 *
 * 背景: allowBackup=true の既定ではアプリデータ全体が対象だが、クラウド自動
 * バックアップには 25MB 上限があり、写真が増えると**全体が黙って**対象外になる。
 * そこで:
 *   - クラウド自動バックアップ = SQLite（DB）と設定のみ（確実に枠内に収まり、
 *     レシピ・記録・在庫のテキストデータは常時 Google 側へ自動保護される）
 *   - 端末間転送（D2D・上限なし）= 写真を含む全データ
 * 写真のクラウド退避はアプリ内の SAF 書き出し / 移行ファイル共有が担う。
 *
 * 注意: ネイティブ設定の変更なので、ローカルビルドへの反映には --prebuild が必要
 * （docs/リリース手順.md）。
 */
const { withAndroidManifest, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const BACKUP_RULES_FILE = 'daidoko_backup_rules.xml';
const DATA_EXTRACTION_RULES_FILE = 'daidoko_data_extraction_rules.xml';

// API 30 以前（fullBackupContent）: クラウド自動バックアップの対象を DB と設定に限定
const BACKUP_RULES_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- generated by plugins/withDaidokoBackupRules.js — 編集しない -->
<full-backup-content>
  <include domain="file" path="SQLite/" />
  <include domain="database" path="." />
  <include domain="sharedpref" path="." />
</full-backup-content>
`;

// API 31+（dataExtractionRules）: クラウドは DB と設定のみ / 端末間転送は写真込み全部
const DATA_EXTRACTION_RULES_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- generated by plugins/withDaidokoBackupRules.js — 編集しない -->
<data-extraction-rules>
  <cloud-backup>
    <include domain="file" path="SQLite/" />
    <include domain="database" path="." />
    <include domain="sharedpref" path="." />
  </cloud-backup>
  <device-transfer>
    <include domain="file" path="." />
    <include domain="database" path="." />
    <include domain="sharedpref" path="." />
  </device-transfer>
</data-extraction-rules>
`;

function withBackupRuleResources(config) {
  return withDangerousMod(config, [
    'android',
    (modConfig) => {
      const xmlDir = path.join(
        modConfig.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml',
      );
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, BACKUP_RULES_FILE), BACKUP_RULES_XML);
      fs.writeFileSync(path.join(xmlDir, DATA_EXTRACTION_RULES_FILE), DATA_EXTRACTION_RULES_XML);
      return modConfig;
    },
  ]);
}

function withBackupManifestAttributes(config) {
  return withAndroidManifest(config, (modConfig) => {
    const application = modConfig.modResults.manifest.application?.[0];
    if (!application) {
      throw new Error('withDaidokoBackupRules: AndroidManifest に application が見つかりません');
    }
    application.$['android:allowBackup'] = 'true';
    application.$['android:fullBackupContent'] = `@xml/${BACKUP_RULES_FILE.replace('.xml', '')}`;
    application.$['android:dataExtractionRules'] =
      `@xml/${DATA_EXTRACTION_RULES_FILE.replace('.xml', '')}`;
    return modConfig;
  });
}

module.exports = function withDaidokoBackupRules(config) {
  return withBackupManifestAttributes(withBackupRuleResources(config));
};
