/**
 * リリース署名を環境変数から与える config plugin（EAS 依存の脱却・Android のみ）。
 *
 * 背景: Android の署名は EAS 管理鍵だったため、AAB を作るたびに EAS の
 * 無料ビルド枠を消費し、**月末に枠が尽きるとリリースが 1 日単位で止まる**
 * （2026-08-28 に 1.12.3 が実際に止まった。さいえん手帳と枠を共有しているため
 * 消費も読めない）。アップロード鍵を EAS からダウンロードしてローカルに置けば、
 * Play は「Play アプリ署名」なのでローカル署名の AAB をそのまま受け付ける。
 *
 * 仕組み: ビルド時に以下の環境変数が**すべて**揃っていれば release を
 * その鍵で署名し、無ければ従来どおり debug 鍵に落ちる（ローカル検証ビルドは
 * 何も設定せずに今までどおり動く）:
 *
 *   DAIDOKO_UPLOAD_STORE_FILE      … keystore.jks の絶対パス（C:\secure\ 配下）
 *   DAIDOKO_UPLOAD_STORE_PASSWORD
 *   DAIDOKO_UPLOAD_KEY_ALIAS
 *   DAIDOKO_UPLOAD_KEY_PASSWORD
 *
 * **鍵とパスワードはリポジトリに置かない**（C:\secure\・コミット禁止 —
 * docs/リリース手順.md §6）。gradle には env 参照だけを書き込むので、
 * このプラグイン自体に秘密は含まれない。
 *
 * 注意: ネイティブ設定の変更なので、ローカルビルドへの反映には --prebuild が必要。
 * 署名後は `keytool -printcert -jarfile <aab>` の SHA-1 が EAS 管理鍵
 * （docs/リリース手順.md の `76:BA:…`）と一致することを確認してから提出する。
 */
const { withAppBuildGradle } = require('@expo/config-plugins');

const MARKER = 'withDaidokoReleaseSigning';

const RELEASE_SIGNING_CONFIG = `
        release {
            // generated by plugins/${MARKER}.js — 編集しない
            if (System.getenv("DAIDOKO_UPLOAD_STORE_FILE")) {
                storeFile file(System.getenv("DAIDOKO_UPLOAD_STORE_FILE"))
                storePassword System.getenv("DAIDOKO_UPLOAD_STORE_PASSWORD")
                keyAlias System.getenv("DAIDOKO_UPLOAD_KEY_ALIAS")
                keyPassword System.getenv("DAIDOKO_UPLOAD_KEY_PASSWORD")
            }
        }`;

function applySigning(gradle) {
  if (gradle.includes(MARKER)) return gradle; // 二重適用しない

  // signingConfigs に release を足す（debug ブロックの直後）
  const debugBlock = /(signingConfigs\s*\{\s*\n\s*debug\s*\{[^}]*\})/m;
  if (!debugBlock.test(gradle)) {
    throw new Error(`${MARKER}: signingConfigs.debug が見つからない（テンプレートが変わった？）`);
  }
  let out = gradle.replace(debugBlock, `$1${RELEASE_SIGNING_CONFIG}`);

  // release ビルドの署名を「env があれば release 鍵・無ければ debug 鍵」に切り替える。
  // テンプレートの release ブロックには目印コメントが付いているのでそこを狙う
  const releaseSigning =
    /(release\s*\{\s*\n(?:\s*\/\/[^\n]*\n)*)(\s*)signingConfig signingConfigs\.debug/m;
  if (!releaseSigning.test(out)) {
    throw new Error(
      `${MARKER}: buildTypes.release の signingConfig signingConfigs.debug が見つからない`,
    );
  }
  out = out.replace(
    releaseSigning,
    `$1$2signingConfig System.getenv("DAIDOKO_UPLOAD_STORE_FILE") ? signingConfigs.release : signingConfigs.debug // ${MARKER}`,
  );
  return out;
}

module.exports = function withDaidokoReleaseSigning(config) {
  return withAppBuildGradle(config, (c) => {
    if (c.modResults.language !== 'groovy') {
      throw new Error(`${MARKER}: groovy 以外の build.gradle には対応していない`);
    }
    c.modResults.contents = applySigning(c.modResults.contents);
    return c;
  });
};

module.exports.applySigning = applySigning; // テスト用
