/**
 * Android のアイコン長押しショートカット「お店の料理を撮る」（R3 / Issue #114）。
 *
 * 店を出た直後の数十秒に最適化した最短経路。設定「アプリを開いたらすぐ撮影」に
 * 依存せず、ホーム画面から 2 アクション（長押し → 選択）で撮影に入れる。
 * 設計は `docs/お店の味を再現設計.md` §4.4。
 *
 * 注意: ネイティブ設定の変更なので、ローカルビルドへの反映には --prebuild が必要
 * （docs/リリース手順.md）。
 */
const { withAndroidManifest, withDangerousMod, withStringsXml } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const SHORTCUTS_FILE = 'daidoko_shortcuts.xml';
const LABEL_KEY = 'daidoko_shortcut_capture_short';
const LONG_LABEL_KEY = 'daidoko_shortcut_capture_long';

// targetPackage / targetClass は生成時に埋める（package は app.json の android.package）
function buildShortcutsXml(androidPackage) {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- generated by plugins/withDaidokoShortcuts.js — 編集しない -->
<shortcuts xmlns:android="http://schemas.android.com/apk/res/android">
  <shortcut
    android:shortcutId="capture-dish"
    android:enabled="true"
    android:icon="@mipmap/ic_launcher"
    android:shortcutShortLabel="@string/${LABEL_KEY}"
    android:shortcutLongLabel="@string/${LONG_LABEL_KEY}">
    <!-- ルートは (tabs) を含めない形（capture-store-screenshots.mjs の deep link と同じ） -->
    <intent
      android:action="android.intent.action.VIEW"
      android:data="daidoko://recipes/import-photo"
      android:targetPackage="${androidPackage}"
      android:targetClass="${androidPackage}.MainActivity" />
  </shortcut>
</shortcuts>
`;
}

function withShortcutResource(config) {
  return withDangerousMod(config, [
    'android',
    (modConfig) => {
      const androidPackage = modConfig.android?.package;
      if (!androidPackage) {
        throw new Error('withDaidokoShortcuts: app.json の android.package が未設定です');
      }
      const xmlDir = path.join(
        modConfig.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml',
      );
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, SHORTCUTS_FILE), buildShortcutsXml(androidPackage));
      return modConfig;
    },
  ]);
}

function withShortcutStrings(config) {
  return withStringsXml(config, (modConfig) => {
    const strings = modConfig.modResults.resources.string ?? [];
    const upsert = (name, value) => {
      const existing = strings.find((item) => item.$?.name === name);
      if (existing) {
        existing._ = value;
        return;
      }
      // translatable=false: ショートカットのラベルは日本語配信のみで翻訳対象にしない
      strings.push({ $: { name, translatable: 'false' }, _: value });
    };
    // 短いラベルはランチャーの表示幅が狭く、長いと省略される
    upsert(LABEL_KEY, 'お店の料理を撮る');
    upsert(LONG_LABEL_KEY, 'お店で食べた料理を撮ってレシピにする');
    modConfig.modResults.resources.string = strings;
    return modConfig;
  });
}

function withShortcutManifestMetaData(config) {
  return withAndroidManifest(config, (modConfig) => {
    const application = modConfig.modResults.manifest.application?.[0];
    if (!application) {
      throw new Error('withDaidokoShortcuts: AndroidManifest に application が見つかりません');
    }
    // meta-data は **ランチャー activity の中** に置く必要がある（application 直下では効かない）
    const launcher = (application.activity ?? []).find((activity) =>
      (activity['intent-filter'] ?? []).some((filter) =>
        (filter.category ?? []).some(
          (category) => category.$?.['android:name'] === 'android.intent.category.LAUNCHER',
        ),
      ),
    );
    if (!launcher) {
      throw new Error('withDaidokoShortcuts: LAUNCHER activity が見つかりません');
    }
    const metaData = launcher['meta-data'] ?? [];
    const name = 'android.app.shortcuts';
    const resource = `@xml/${SHORTCUTS_FILE.replace('.xml', '')}`;
    const existing = metaData.find((item) => item.$?.['android:name'] === name);
    if (existing) {
      existing.$['android:resource'] = resource;
    } else {
      metaData.push({ $: { 'android:name': name, 'android:resource': resource } });
    }
    launcher['meta-data'] = metaData;
    return modConfig;
  });
}

module.exports = function withDaidokoShortcuts(config) {
  return withShortcutManifestMetaData(withShortcutStrings(withShortcutResource(config)));
};
